/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LatihanTugas3.java
 *
 * Created on Jul 27, 2017, 2:30:56 PM
 */
package tugas3java3;

import java.awt.Font;

/**
 *
 * @author INDOPORCELAIN
 */
public class LatihanTugas3 extends javax.swing.JFrame {

    /** Creates new form LatihanTugas3 */
    public LatihanTugas3() {
        initComponents();
    }
   
    private void getStyle(){
        Font font = null;
        
        if(cbBold.isSelected() && cbItalic.isSelected() && cbPerbesar.isSelected())
            font = new Font("Serif", Font.BOLD + Font.ITALIC,25);
        else if(cbBold.isSelected() && cbItalic.isSelected() )
            font = new Font("Serif", Font.BOLD + Font.ITALIC,14);
        else if(cbPerbesar.isSelected() && cbItalic.isSelected() )
            font = new Font("Serif", Font.PLAIN + Font.ITALIC,25);
        else if(cbBold.isSelected() && cbPerbesar.isSelected() )
            font = new Font("Serif", Font.BOLD + Font.PLAIN,25);
        else if(cbBold.isSelected())
            font = new Font("Serif", Font.BOLD, 14);
        else if(cbItalic.isSelected())
            font = new Font("Serif", Font.ITALIC, 14);
         else if(cbPerbesar.isSelected())
            font = new Font("Serif", Font.PLAIN ,25);
        else
            font = new Font("Serif", Font.PLAIN,14);
        lblText.setFont(font);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblText = new javax.swing.JLabel();
        cbBold = new javax.swing.JCheckBox();
        cbItalic = new javax.swing.JCheckBox();
        cbPerbesar = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblText.setText("Tesk Ini Akan Berubah");

        cbBold.setText("Bold");
        cbBold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBoldActionPerformed(evt);
            }
        });

        cbItalic.setText("Italic");
        cbItalic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbItalicActionPerformed(evt);
            }
        });

        cbPerbesar.setText("Perbesar");
        cbPerbesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPerbesarActionPerformed(evt);
            }
        });

        jLabel1.setText("Pilih");

        jMenu1.setText("File");

        jMenu2.setText("Exit");
        jMenu1.add(jMenu2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbItalic)
                            .addComponent(cbBold)
                            .addComponent(cbPerbesar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBold)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbItalic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbPerbesar)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbBoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBoldActionPerformed
        // TODO add your handling code here:
        getStyle();
    }//GEN-LAST:event_cbBoldActionPerformed

    private void cbItalicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbItalicActionPerformed
        // TODO add your handling code here:
        getStyle();
    }//GEN-LAST:event_cbItalicActionPerformed

    private void cbPerbesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPerbesarActionPerformed
        // TODO add your handling code here:
        getStyle();
    }//GEN-LAST:event_cbPerbesarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LatihanTugas3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbBold;
    private javax.swing.JCheckBox cbItalic;
    private javax.swing.JCheckBox cbPerbesar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblText;
    // End of variables declaration//GEN-END:variables
}
