/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Tugas3.java
 *
 * Created on Jul 27, 2017, 1:50:14 PM
 */
package tugas3java3;

/**
 *
 * @author INDOPORCELAIN
 */
public class Tugas3 extends javax.swing.JFrame {

    /** Creates new form Tugas3 */
    public Tugas3() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgJenkel = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtLahir = new javax.swing.JTextField();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        cbOlahraga = new javax.swing.JCheckBox();
        cbBaca = new javax.swing.JCheckBox();
        cbJalan = new javax.swing.JCheckBox();
        cbTidur = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHasil = new javax.swing.JTextArea();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama");

        jLabel2.setText("TTL");

        jLabel3.setText("Jenis Kelamin");

        jLabel4.setText("Hobi");

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        txtLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLahirActionPerformed(evt);
            }
        });

        bgJenkel.add(rbLaki);
        rbLaki.setText("Laki - Laki");

        bgJenkel.add(rbPerempuan);
        rbPerempuan.setText("Perempuan");

        cbOlahraga.setText("Olahraga");
        cbOlahraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOlahragaActionPerformed(evt);
            }
        });

        cbBaca.setText("Membaca");

        cbJalan.setText("Jalan");

        cbTidur.setText("Tidur");

        txtHasil.setColumns(20);
        txtHasil.setRows(5);
        jScrollPane1.setViewportView(txtHasil);

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbLaki)
                            .addComponent(cbOlahraga)
                            .addComponent(cbJalan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTidur)
                            .addComponent(cbBaca)
                            .addComponent(rbPerempuan))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOk))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(rbLaki)
                            .addComponent(rbPerempuan))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbOlahraga)
                            .addComponent(cbBaca))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbJalan)
                        .addComponent(cbTidur))
                    .addComponent(btnOk))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLahirActionPerformed

    private void cbOlahragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOlahragaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbOlahragaActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        if(txtNama.getText().equals("")||txtLahir.getText().equals("")||bgJenkel.getSelection().equals("")){
           txtHasil.setText("Harus Di Isi");
        } else{
       String Jenkel;
       StringBuilder hobi = new StringBuilder();
       if(rbLaki.isSelected())
           Jenkel="Laki-Laki";
       else
           Jenkel="Perempuan";
	
       if(cbBaca.isSelected()){
                hobi.append(cbBaca.getText()).append(""+",");
       }
       if(cbOlahraga.isSelected()){
                hobi.append(cbOlahraga.getText()).append(""+",");
       }
       if(cbJalan.isSelected()){
                hobi.append(cbJalan.getText()).append(""+",");
       }
       if(cbTidur.isSelected()){
                hobi.append(cbTidur.getText()).append(""+",");
       }
           
      txtHasil.setText("Nama : "+txtNama.getText()+"\n" +"Lahir : "+txtLahir.getText()+"\n"+"Jenis Kelamin : "
              + ""+Jenkel+"\n"+"Hobi : "+hobi.toString());
    }                                     


    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Tugas3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgJenkel;
    private javax.swing.JButton btnOk;
    private javax.swing.JCheckBox cbBaca;
    private javax.swing.JCheckBox cbJalan;
    private javax.swing.JCheckBox cbOlahraga;
    private javax.swing.JCheckBox cbTidur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTextArea txtHasil;
    private javax.swing.JTextField txtLahir;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
